Talent:
  Jury:
    UUID:
  Locations:
    Spawn:
      World:
      X:
      Y:
      Z:
      Yaw:
      Pitch:
    Stage:
      World:
      X:
      Y:
      Z:
      Yaw:
      Pitch:
    End:
      World:
      X:
      Y:
      Z:
      Yaw:
      Pitch:
    Sound:
      World:
      X:
      Y:
      Z:
    OnStage:
      World:
      X:
      Y:
      Z:
  NextPlayers:
